application: slothdraw
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: static/img/favicon.ico
  upload: favicon\.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: robots\.txt

- url: /static
  static_dir: static

- url: /.*
  script: slothdraw.app

libraries:
- name: jinja2
  version: latest
